<?php

namespace Test\AbraFlexi\Bricks;

use AbraFlexi\Bricks\Change;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-11-23 at 23:27:05.
 */
class ChangeTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Change
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Change();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers AbraFlexi\Bricks\Change::getData
     * @todo   Implement testgetData().
     */
    public function testgetData()
    {
        $this->assertEquals('', $this->object->getData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Bricks\Change::setData
     * @todo   Implement testsetData().
     */
    public function testsetData()
    {
        $this->assertEquals('', $this->object->setData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}