<?php

namespace Test\AbraFlexi\Bricks;

use AbraFlexi\Bricks\Changes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-11-23 at 23:27:05.
 */
class ChangesTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Changes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Changes();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers AbraFlexi\Bricks\Changes::dataDiff
     * @todo   Implement testdataDiff().
     */
    public function testdataDiff()
    {
        $this->assertEquals('', $this->object->dataDiff());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}