<?php

declare(strict_types=1);

/**
 * This file is part of the BricksForAbraFlexi package
 *
 * https://github.com/VitexSoftware/php-abraflexi-bricks
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Bricks;

use AbraFlexi\Bricks\GateKeeper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-24 at 16:45:31.
 */
class GateKeeperTest extends \Test\Ease\SandTest
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new GateKeeper();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Bricks\GateKeeper::isAccessibleBy
     *
     * @todo   Implement testIsAccessibleBy().
     */
    public function testIsAccessibleBy(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Bricks\GateKeeper::getDocumentCompany
     *
     * @todo   Implement testGetDocumentCompany().
     */
    public function testGetDocumentCompany(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Bricks\GateKeeper::getCustomerCompany
     *
     * @todo   Implement testGetCustomerCompany().
     */
    public function testGetCustomerCompany(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }
}
