<?php

declare(strict_types=1);

/**
 * This file is part of the BricksForAbraFlexi package
 *
 * https://github.com/VitexSoftware/php-abraflexi-bricks
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Bricks;

use AbraFlexi\Bricks\PotvrzeniUhrady;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-11-23 at 23:27:05.
 */
class PotvrzeniUhradyTest extends \PHPUnit\Framework\TestCase
{
    protected PotvrzeniUhrady $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        if (class_exists('\Ease\HtmlMailer')) {
            // Create a mock document for testing
            $mockDocument = $this->createMock(\AbraFlexi\Document::class);
            $mockDocument->method('getDataValue')->willReturn('test');
            $mockDocument->method('getEmail')->willReturn('test@example.com');

            $this->object = new PotvrzeniUhrady($mockDocument);
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Bricks\PotvrzeniUhrady::__construct
     */
    public function testConstruct(): void
    {
        if (!class_exists('\Ease\HtmlMailer')) {
            $this->markTestSkipped('Ease\HtmlMailer class is not available. Please install vitexsoftware/ease-core package.');

            return;
        }

        $this->assertInstanceOf(PotvrzeniUhrady::class, $this->object);
    }
}
