<?php

namespace Test\AbraFlexi\Bricks;

use AbraFlexi\Bricks\PotvrzeniUhrady;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-11-23 at 23:27:05.
 */
class PotvrzeniUhradyTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var PotvrzeniUhrady
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new PotvrzeniUhrady();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

}
