<?php

declare(strict_types=1);

/**
 * This file is part of the BricksForAbraFlexi package
 *
 * https://github.com/VitexSoftware/php-abraflexi-bricks
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Bricks\ConvertRules;

use AbraFlexi\Bricks\ConvertRules\FakturaPrijata_to_FakturaVydana;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-11-23 at 23:27:06.
 */
class FakturaPrijata_to_FakturaVydanaTest extends \PHPUnit\Framework\TestCase
{
    protected FakturaPrijata_to_FakturaVydana $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new FakturaPrijata_to_FakturaVydana();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }
}
