<?php

declare(strict_types=1);

/**
 * This file is part of the BricksForAbraFlexi package
 *
 * https://github.com/VitexSoftware/php-abraflexi-bricks
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Bricks\ConvertRules;

use AbraFlexi\Bricks\ConvertRules\FakturaPrijata_to_Zavazek;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-25 at 11:19:13.
 */
class FakturaPrijata_to_ZavazekTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new FakturaPrijata_to_Zavazek();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Bricks\ConvertRules\FakturaPrijata_to_Zavazek::polozkyFakturyTypPolozkyK
     *
     * @todo   Implement testPolozkyFakturyTypPolozkyK().
     */
    public function testPolozkyFakturyTypPolozkyK(): void
    {
        $this->assertEquals('', $this->object->PolozkyFakturyTypPolozkyK('test'));
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
