<?php

namespace Test\AbraFlexi\Bricks\ConvertRules;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-25 at 11:19:26.
 */
class FakturaVydana_to_PokladniPohybTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var FakturaVydana_to_PokladniPohyb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new FakturaVydana_to_PokladniPohyb();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
