<?php

namespace Test\AbraFlexi\Bricks\ConvertRules;

use AbraFlexi\Bricks\ConvertRules\FakturaPrijata_to_FakturaVydana;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-11-23 at 23:27:06.
 */
class FakturaPrijata_to_FakturaVydanaTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var FakturaPrijata_to_FakturaVydana
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new FakturaPrijata_to_FakturaVydana();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}