<?php

declare(strict_types=1);

/**
 * This file is part of the BricksForAbraFlexi package
 *
 * https://github.com/VitexSoftware/php-abraflexi-bricks
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Bricks\ConvertRules;

use AbraFlexi\Bricks\ConvertRules\FakturaVydana_to_PokladniPohyb;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-25 at 11:19:26.
 */
class FakturaVydana_to_PokladniPohybTest extends \PHPUnit\Framework\TestCase
{
    protected FakturaVydana_to_PokladniPohyb $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new FakturaVydana_to_PokladniPohyb();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Bricks\ConvertRules\FakturaVydana_to_PokladniPohyb::__construct
     */
    public function testConstruct(): void
    {
        $this->assertInstanceOf(FakturaVydana_to_PokladniPohyb::class, $this->object);
    }
}
