<?php

declare(strict_types=1);

/**
 * This file is part of the BricksForAbraFlexi package
 *
 * https://github.com/VitexSoftware/php-abraflexi-bricks
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Bricks\ConvertRules;

use AbraFlexi\Bricks\ConvertRules\FakturaPrijataPolozka_to_Cenik;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-10-02 at 12:20:43.
 */
class FakturaPrijataPolozka_to_CenikTest extends \PHPUnit\Framework\TestCase
{
    protected FakturaPrijataPolozka_to_Cenik $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new FakturaPrijataPolozka_to_Cenik();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Bricks\ConvertRules\FakturaPrijataPolozka_to_Cenik::__construct
     */
    public function testConstruct(): void
    {
        $this->assertInstanceOf(FakturaPrijataPolozka_to_Cenik::class, $this->object);
    }
}
