<?php

namespace Test\AbraFlexi\Bricks\ConvertRules;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-25 at 11:19:13.
 */
class FakturaPrijata_to_ZavazekTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var FakturaPrijata_to_Zavazek
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new FakturaPrijata_to_Zavazek();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers AbraFlexi\Bricks\ConvertRules\FakturaPrijata_to_Zavazek::polozkyFakturyTypPolozkyK
     * @todo   Implement testPolozkyFakturyTypPolozkyK().
     */
    public function testPolozkyFakturyTypPolozkyK()
    {
        $this->assertEquals('', $this->object->PolozkyFakturyTypPolozkyK());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
