<?php

namespace Test\AbraFlexi\ui;

use AbraFlexi\ui\AbraFlexiLogo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-10-04 at 20:24:47.
 */
class AbraFlexiLogoTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var AbraFlexiLogo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new AbraFlexiLogo();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}