<?php

namespace Test\AbraFlexi\ui;

use AbraFlexi\ui\CompanyLogo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-10-04 at 20:24:48.
 */
class CompanyLogoTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var CompanyLogo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new CompanyLogo();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

}
