<?php

namespace Test\AbraFlexi\ui;

use AbraFlexi\ui\DocumentLink;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-10-04 at 20:24:48.
 */
class DocumentLinkTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var DocumentLink
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new DocumentLink();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}