<?php

namespace Test\AbraFlexi\ui;

use AbraFlexi\ui\RecordChooser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-10-04 at 20:24:47.
 */
class RecordChooserTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var RecordChooser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new RecordChooser();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\ui\RecordChooser::selectize
     * @todo   Implement testselectize().
     */
    public function testselectize() {
        $this->assertEquals('', $this->object->selectize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
