<?php

namespace Test\AbraFlexi\ui;

use AbraFlexi\ui\SearchBox;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-10-04 at 20:24:48.
 */
class SearchBoxTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var SearchBox
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new SearchBox();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\ui\SearchBox::afterAdd
     * @todo   Implement testafterAdd().
     */
    public function testafterAdd() {
        $this->assertEquals('', $this->object->afterAdd());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\ui\SearchBox::finalize
     * @todo   Implement testfinalize().
     */
    public function testfinalize() {
        $this->assertEquals('', $this->object->finalize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
